[package]
name = "day25"
version = "0.1.0"
authors = ["lucifer <lucifer.hemp@fau.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day25"
path = "main.rs"
