[package]
name = "day15"
version = "0.1.0"
authors = ["Lucifer <lucifer.hemp@fau.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.2.1"
num = "0.4.0"

[[bin]]
name = "day15"
path = "main.rs"
