[package]
name = "day8"
version = "0.1.0"
authors = ["Lucifer <lucifer.hemp@fau.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day5"
path = "main.rs"
